# Generated by Django 4.1.7 on 2023-03-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Набор символов не более 150', max_length=150, verbose_name='Имя'),
        ),
    ]
